# Delete person group
DELETE {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# Create person group
PUT {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}

{
    "name": "Microsoft Technical Trainers",
    "recognitionModel": "recognition_04"
}
###

# Get person group
GET {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# Add person to person group
# @name person
POST {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/persons
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}

{
    "name": "Johan Myburgh",
    "userData": "Some optional data"
}
###

# Get person
GET {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/persons/{{person.response.body.personId}}
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# List persons in person group
GET {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/persons
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# Add face to person
POST {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/persons/{{person.response.body.personId}}/persistedFaces
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
Content-Type: application/octet-stream

< C:\Sampledata\me\six.jpg
# < {{faceTrainingPath}}2.jpg
# < {{faceTrainingPath}}3.jpg
# < {{faceTrainingPath}}4.jpg
# < {{faceTrainingPath}}5.jpg
# < {{faceTrainingPath}}6.jpg
# < {{faceTrainingPath}}7.jpg
###

# List persons in person group (now the faces have been added)
GET {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/persons
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# Train person group
POST {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/train
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# Get training status (URL found in Operation-Location header of the train person group response)
GET {{Api-Url-Face}}face/v1.0/persongroups/{{personGroupName}}/training
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
###

# Detect face (get FaceId)
# @name faceId
POST {{Api-Url-Face}}face/v1.0/detect
    ?returnFaceId=true
    &returnFaceLandmarks=true
    &returnRecognitionModel=false
    &faceIdTimeToLive=86400
    &recognitionModel=recognition_04
    &detectionModel=detection_03
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}
Content-Type: application/octet-stream

< C:\Sampledata\me\six.png

###

# Verify face
POST {{Api-Url-Face}}face/v1.0/verify
Ocp-Apim-Subscription-Key: {{Api-Key-Face}}

{
    "faceId": "{{faceId.response.body.*.faceId}}",
    "personId": "{{person.response.body.personId}}",
    "personGroupId": "{{personGroupName}}"
}